"""initial schema

Revision ID: c48e17cf7704
Revises: 
Create Date: 2026-03-26 23:44:13.533060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c48e17cf7704'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cache_entries',
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('courses',
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=10), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('avg_gpa', sa.Float(), nullable=True),
    sa.Column('gen_eds', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('prerequisites_raw', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('degree_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('requirement_group', sa.String(length=100), nullable=False),
    sa.Column('requirement_type', sa.Enum('CORE', 'ELECTIVE', 'GENED', name='requirement_type_enum'), nullable=False),
    sa.Column('course_options', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('credits_needed', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('professors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('courses_taught', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('minor', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('completed_courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('grade', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sections',
    sa.Column('section_id', sa.String(length=30), nullable=False),
    sa.Column('course_id', sa.String(length=20), nullable=False),
    sa.Column('professor_id', sa.UUID(), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=False),
    sa.Column('days', sa.String(length=10), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('total_seats', sa.Integer(), nullable=False),
    sa.Column('open_seats', sa.Integer(), nullable=False),
    sa.Column('waitlist', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('section_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sections')
    op.drop_table('reviews')
    op.drop_table('completed_courses')
    op.drop_table('users')
    op.drop_table('professors')
    op.drop_table('degree_requirements')
    op.drop_table('courses')
    op.drop_table('cache_entries')
    # ### end Alembic commands ###
